version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - mongo-network
    depends_on:
      - database
    volumes:
      - ../:/opt/sharex
    environment:
      DEVELOPMENT: ${DEV}
      PORT: ${APP_PORT}
      USE_MONGO: ${USE_MONGO}
      API_KEY: ${API_KEY}

  database:
    restart: unless-stopped
    image: mongo:4.4.13-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: sharex
      MONGO_INITDB_ROOT_PASSWORD: sharex
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge